title: My Blog
description: My personal blog
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  main:
    - title: Study
      url: /study/
    - title: APP
      url: /app/
    - title: Contact
      url: /contact/
  footer:
    - title: Privacy Policy
      url: /privacy-policy/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 